### ISSUE TITLE
select an unescaped field (e.g. a function)

### ISSUE THREAD

**Issue by einfallstoll** [PHPixie/Database#4]
I came across a problem using functions with this component. The SQL query I'd like to execute:

```
SELECT md5(random()::text || clock_timestamp()::text)::uuid
```

When using the component I end up with the following:

```
$result = $query
            ->table('pg_language')
            ->fields(array(
                'md5(random()::text || clock_timestamp()::text)::uuid'
            ))
            ->execute();

// Query: SELECT "md5(random()::text || clock_timestamp()::text)::uuid"
// The field will be handled as a column name and ends up in an error
```

I created an ugly workaround to achieve my goal:

```
$result = $query
            ->table('pg_language')
            ->fields(array(
                'lanname", md5(random()::text || clock_timestamp()::text)::uuid AS UUID, "lanowner'
            ))
            ->execute();
// Query: SELECT "lanname", md5(random()::text || clock_timestamp()::text)::uuid AS UUID, "lanowner" FROM "pg_language"
```

I recommend to add a new function like `fields` but name it `unescapedFields` or something.

**Comment by dracony** [comment]
You can do that with ->fields($database->sqlExpression("md5...."));
SQLExpression also allows parametrized expressions, e.g. ->sqlExpression('b = ?', array(1));

**Comment by einfallstoll** [comment]
Where's the documentation to this?

**Comment by dracony** [comment]
In the README, just look for 'sqlExpression'

**Comment by einfallstoll** [comment]
Maybe there should be a TOC... Haven't seen this. Thanks.
